### ISSUE TITLE
Part/Mirror does not gets imported

### ISSUE THREAD

**Issue by polemidis** [kbwbe/A2plus#108]
Hello guys, thats maybe a quick fix. 
When I import a part where a body is mirrored with the Part/Mirror,  the mirror bodyt is imported but not the original body.

Is this intentional? I have a turnaround by making a fussion between the 2 bodies, but why adding more steps?

Thank you for the great job! 
P.S. Do you want to put new issues that I found here or in the freecad forum?

**Comment by kbwbe** [comment]
Thanks for the hint ! This is a bug. Reporting bugs here on Github is sufficient. I look regularly to issues.

**Comment by polemidis** [comment]
Perfect man! As I am transitioning into A2+ I will post here whatever I found. Thank you!

**Comment by kbwbe** [comment]
Fixed with PR #110 
V0.1.4.1 is working now for this.
