### ISSUE TITLE
duplicate part not working

### ISSUE THREAD

**Issue by Turro75** [kbwbe/A2plus#11]
Hello,

I modified importpart.py in line 335 from:
    if hasattr(newObj.ViewObject, p) and p not in ['DiffuseColor','Proxy']:
to:
    if hasattr(newObj.ViewObject, p) and p not in ['DiffuseColor','Proxy','MappedColors']:

now duplicate works again

Best Regards

**Comment by kbwbe** [comment]
Merged..
