### ISSUE TITLE
Compatibility issue with Fasteners workbench

### ISSUE THREAD

**Issue by polemidis** [kbwbe/A2plus#119]
Hello, I hope I not annoying you!.
I found another weird behavior. Again on my firewood processor project.
If you open the "saw bar assembly.fcstd" you will see a bolt with some washers and nuts.
Now, this assembly is imported to the "0-Master  CAD.fcstd". You can see that the bolt is missing!
Going back, the bolt was imported when there were no nuts or washers, but as soon as I added these to the assembly the bolt stop being imported to the Master CAD.

I can also post this issue to the Fasteners page if you think its something in their code.

Thank you for your effort!!!

**Comment by kbwbe** [comment]
Hi Polemidis,
i could reproduce the problem. But mixing up a2p parts and other types (fasteners, a thickness is also inside) is not the recommended way to work with A2plus. I just selected the bolt, used the convert part command and after that the bolt was present in a main assembly. It is much better to convert each fastener, if the assembly shall be used as subassembly furtheron.

**Comment by polemidis** [comment]
ok thank you! I thought the convert was referring to the constraints :)
