### ISSUE TITLE
After installing a2plus

### ISSUE THREAD

**Issue by brandonroger** [kbwbe/A2plus#127]
Hi, I've tried to install A2plus, and I got this error : 

Program received signal SIGSEGV, Segmentation fault.
#0  /lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7f3c10800f20]
#1  0x7f3c112f16fd in QObject::setObjectName(QString const&) from /usr/lib/x86_64-linux-gnu/libQtCore.so.4+0xd
#2  0x7f3c1345ee0e in Gui::WorkbenchGroup::setWorkbenchData(int, QString const&) from /usr/lib/freecad/lib/libFreeCADGui.so+0xae
#3  0x7f3c1345f451 in Gui::WorkbenchGroup::refreshWorkbenchList() from /usr/lib/freecad/lib/libFreeCADGui.so+0x221
#4  0x7f3c1345f5f5 in Gui::WorkbenchGroup::addTo(QWidget*) from /usr/lib/freecad/lib/libFreeCADGui.so+0x25
#5  0x7f3c134682df in Gui::CommandManager::addTo(char const*, QWidget*) from /usr/lib/freecad/lib/libFreeCADGui.so+0x1bf
#6  0x7f3c137296dc in Gui::MenuManager::setup(Gui::MenuItem*, QMenu*) const from /usr/lib/freecad/lib/libFreeCADGui.so+0x61c
#7  0x7f3c13729d71 in Gui::MenuManager::setup(Gui::MenuItem*) const from /usr/lib/freecad/lib/libFreeCADGui.so+0x1c1
#8  0x7f3c13740566 in Gui::Workbench::activate() from /usr/lib/freecad/lib/libFreeCADGui.so+0x96
#9  0x7f3c13741b1b in Gui::WorkbenchManager::activate(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) from /usr/lib/freecad/lib/libFreeCADGui.so+0x1b
#10  0x7f3c133f818d in Gui::Application::activateWorkbench(char const*) from /usr/lib/freecad/lib/libFreeCADGui.so+0xa7d
#11  0x7f3c1340553c in Gui::Application::sActivateWorkbenchHandler(_object*, _object*, _object*) from /usr/lib/freecad/lib/libFreeCADGui.so+0x6c
#12  /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x8010) [0x7f3c123ea1d0]
#13  /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7d8) [0x7f3c1251a278]
#14  /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalCode+0x19) [0x7f3c123e2029]
#15  /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyRun_StringFlags+0x76) [0x7f3c12485546]
#16  0x7f3c12964b46 in Base::InterpreterSingleton::runString[abi:cxx11](char const*) from /usr/lib/freecad/lib/libFreeCADBase.so+0x66
#17  0x7f3c133fa76a in Gui::Application::runApplication() from /usr/lib/freecad/lib/libFreeCADGui.so+0xdfa
#18  freecad(main+0x6db) [0x561f8e91c4db]
#19  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f3c107e3b97]
#20  freecad(_start+0x2a) [0x561f8e91d68a]

OS : Ubuntu 18.04
FreeCAD version : 0.17

**Comment by kbwbe** [comment]
Hi, this seems to be more a problem of FC0.17 on Ubuntu 18.04. Do you have the possibility to test with FC0.18-daily ?

**Comment by brandonroger** [comment]
Thanks, I'm going to test it.

**Comment by brandonroger** [comment]
I'd tried, it still doesn't work.

**Comment by brandonroger** [comment]
I tried. It still doesn't work.

**Comment by kbwbe** [comment]
It should even work with FC0.16,17,18. Your whole FC is being crashed within the library "/lib/x86_64-linux-gnu/libc.so.6". A pure python program, as A2plus is, usually does not cause such effects. In another issue FC was crashed by a buggy libexpat library on Ubuntu 18.04 (Partlist crash). After downgrading the libexpat, at least the crash was avoided.

To make sure, that the problem does nothing have to do with the libs installed on your system, you should test the AppImage Version. I tested with this one: 
FreeCAD_0.18.15403.glibc2.17-x86_64.AppImage
A2plus from master branch and recent devel branch are cleanly starting up.

**Comment by kbwbe** [comment]
P.S: My system information for the AppImage test mentioned above:
OS: Linux Mint 18.3 Sylvia
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.15403 (Git) AppImage
Build type: Release
Branch: master
Hash: 44e8f9e9bf3b7a93e927c97b19c6d2850fd75f19
Python version: 2.7.6
Qt version: 4.8.6
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: German/Germany (de_DE)

**Comment by kbwbe** [comment]
Not to reproduce, no complains of other users ATM.
Therefore: issue closed.
