### ISSUE TITLE
A2p releasecandidate is not py3 compatible

### ISSUE THREAD

**Issue by easyw** [kbwbe/A2plus#138]
I have some issue with the 'Constraint Tool' dialog and the 'Constraint property' dialog
Adding a constraint will give the following error:
tested with (FreeCAD_0.18.15481_Conda_Py3QT5-WinVS2015_x64.7z)

> Running the Python command 'a2p_ConstraintDialogCommand' failed:
> Traceback (most recent call last):
>   File "C:\Users\mau\AppData\Roaming\FreeCAD\Mod\A2plus\a2p_constraintDialog.py", line 821, in Activated
>     p = a2p_ConstraintPanel()
>   File "C:\Users\mau\AppData\Roaming\FreeCAD\Mod\A2plus\a2p_constraintDialog.py", line 784, in __init__
>     self.move(screen_center(self))      
>   File "C:\Users\mau\AppData\Roaming\FreeCAD\Mod\A2plus\a2p_constraintDialog.py", line 783, in <lambda>
>     screen_center = lambda widget: QtGui.QApplication.desktop().screen().rect().center()- widget.rect().center()  
> 
> Internal C++ object (PySide2.QtWidgets.QWidget) already deleted.

**Comment by kbwbe** [comment]
Thanks to reporting. All testers have same result with Py3/Qt5. The dialog window (dockWidget) seems to get destroyed before it can be centered on screen. This does not happen on Py2 systems. I do not have right clue ATM. I took the idea to use dockwidgets from your manipulator wb, as i need dialogs to stay on top of application but not on top of whole desktop. Did you recognize something similar with manipulator WB ?

**Comment by kbwbe** [comment]
Should be done with recent commit. On Conda build appimage, Py3/Qt5, it works for me.

**Comment by easyw** [comment]
> I took the idea to use dockwidgets from your manipulator wb, as i need dialogs to stay on top of application but not on top of whole desktop. Did you recognize something similar with manipulator WB ?

I have a feeling that I did approach a similar issue in Manipulator WB, but I don't remember in which way I tricked it... anyway I'm glad you solved it 😺
