### ISSUE TITLE
About the new way of editing of constraint parameters

### ISSUE THREAD

**Issue by polemidis** [kbwbe/A2plus#152]
Hello just a few comments on the new window for "edit a selected constraint"

Personally I do not like that I can no longer edit the values of the constraint on the Property Box on the left. Is that any way that this will be still available? 
If not the new pop-up window with the constraint properties needs an enhancement plz! The user should be able to adjust the value with the scroll mouse as it generally the common approach in Freecad. 

Great job man!
(p.s. the Partlist now works in ubuntu 18.10)

**Comment by polemidis** [comment]
Also if the user do not put the measurement unit it should used the default unit. For example I use inches. If I put a numeric value it think I put milimeters

**Comment by polemidis** [comment]
A double click on the constraint may should open the edit constraint window

**Comment by kbwbe** [comment]
As first fix i will activate the constraint properties in editor again.

**Comment by polemidis** [comment]
Hey man, these are just my suggestions, and plz do not take my comments as bad criticism. I respect your offer in this project! 
Thanx!

**Comment by kbwbe** [comment]
With new release V0.2.6, the constraint properties are now accessible again in property editor. At least for newly set constraints. But there is no autosolving possible here. (I had to remove this due to nested recomputes). So you have to hit the solve button after using the properties editor.
