### ISSUE TITLE
icon tooltips are inconsistently named

### ISSUE THREAD

**Issue by donovaly** [kbwbe/A2plus#172]
This is a very minor issue but I notice this every time I work with a2plus:

- move the mouse over the different icons in the toolbar

result: sometimes the tooltip text begins with capital letters, sometimes not. 

solutions:
- For a "professional feeling" ;-) all tooltips should begin with a capital letter.
- All tooltips should have the same structure describing the feature. This is already the case for most icons, but for example the icon to edit a part has only "edit" as tooltip.

**Comment by kbwbe** [comment]
The tooltips have been reviewed and improved. Please see release V0.3.3.

**Comment by donovaly** [comment]
Many thanks! You are quick.
