### ISSUE TITLE
missing documentation

### ISSUE THREAD

**Issue by donovaly** [kbwbe/A2plus#173]
I searched around and cannot find a proper documentation. I already wrote some docs for different programs and if you like, I could set up some Wiki pages here in GitHub or we ask the FC guys idf I can ass Wiki pages there.
I think a documentation would be helpful because e.g. for new users is is not clear why a2plus does not take into account that an already assembled part that is later on modified is not taken into account with the current shape but with the shape when it was assembled. Or it is not clear what is the most suitable way to replace a part in an assembly.

**Comment by walterwissmann** [comment]
I work with 'MasterSketches' and LOT-technic.
The transparency cubes are placeholders to bind the part in the room.
To see all i switch off the mastercube inner the subassembly and switch on the part:
![lot_ii](https://user-images.githubusercontent.com/42293697/52523143-656aff80-2c8e-11e9-84fe-ae1b982dad55.jpeg)
![lot_iia](https://user-images.githubusercontent.com/42293697/52523144-68fe8680-2c8e-11e9-9063-8c05e5208b2c.jpeg)

**Comment by donovaly** [comment]
> I work with 'MasterSketches' and LOD-technic...

Interesting and I think these methods should be explained in the docs. If @kbwbe gives me a go I will set up at first the basic documentation and then write a special chapter for methods and concepts like yours.

**Comment by walterwissmann** [comment]
the question is: on witch place should the wiki for a2+ come?

I think it should come to the FreeCAD-Wiki, not on github...

**Comment by kbwbe** [comment]
@donovaly:
Here is the: GO!
Preferred place is the FreeCAD wiki, if we will get access.

**Comment by ManuelKrause** [comment]
Hi @donovaly ,
you can find the preliminary documentation WIP at the bottom paragraphs of https://github.com/kbwbe/A2plus, it's in the README.md file. I haven't bothered with creating some WIKI style documentation so far, as I'm not experienced with it. 
I was quite impressed from the WIKI that can be found for the good old "assembly2" workbench here: https://github.com/hamish2014/FreeCAD_assembly2/wiki

But these words shouldn't interfere your creative process in any way.
All your help is definitely highly appreciated !
Best regards,
Manuel

**Comment by donovaly** [comment]
I got the Go also from the FC devs. The documentation will be here:
https://www.freecadweb.org/wiki/External_workbenches

So I will start as soon as possible and of course take into account the info from
https://github.com/kbwbe/A2plus/blob/master/README.md

**Comment by walterwissmann** [comment]
Hi @donovaly 
> > I work with 'MasterSketches' and LOD-technic...
> 
> Interesting and I think these methods should be explained in the docs. 

Here is an attempt to explain how to easily control complicated data structures with A2Plus.
https://forum.freecadweb.org/viewtopic.php?style=4&f=24&t=34101&p=286367#p286342
Please also scroll up and down...

It is not complete yet.
I have yet to represent the simple control options with A2Plus ...
I hope in the near future could be installed simple aids with A2Plus, which support the handling.

**Comment by donovaly** [comment]
The documentation is almost ready: https://www.freecadweb.org/wiki/A2plus_Workbench#Part_Lists

@walterwissmann : your BIM work is very interesting and useful to know about but it is too complex for the Wiki page describing the basic A2plus stuff. Therefore please create a new Wiki page and make a tutorial out of it.
Here are nice tutorials where you can steal some Wiki formatting ideas:
https://www.freecadweb.org/wiki/Tutorials
and there is also a BIM tutorial:
https://www.freecadweb.org/wiki/Manual:BIM_modeling

You can get Wiki access here: https://forum.freecadweb.org/viewtopic.php?f=21&t=6830
