### ISSUE TITLE
Contraint define dialog is always completely disabled

### ISSUE THREAD

**Issue by donovaly** [kbwbe/A2plus#185]
- open the constraint define dialog.

result: no matter what you have selected before opening the dialog, it is always completely disabled:

![constraintdefinedialog](https://user-images.githubusercontent.com/1828501/52671833-72048780-2f1c-11e9-937c-5dc44f5d5000.jpg)

besides this, the dialog has also no default focus button. (Should be the help button)

**Comment by kbwbe** [comment]
On my system (Linux Mint 18.3) buttons according to previous selection are activated.
Does this not work on Win ?

**Comment by kbwbe** [comment]
This dialog stays on top of application until you close it. According to recent selection the suitable buttons get activated.

**Comment by donovaly** [comment]
> according to previous selection are activated. Does this not work on Win ?

No, this doesn't work. I can select what I want but all buttons in the dialog remain greyed-out.

Also keeping the dialog open and select something does not help.

**Comment by walterwissmann** [comment]
@donovaly 
i also have freecad  on win 7.

Take a click to the background and then click to the 2 things you will give the constrain. 
Then the previous selection should be activated

**Comment by donovaly** [comment]
> Take a click to the background and then click to the 2 things you will give the constrain.

OK, then I get possible constraints in the dialog. And I only tried to select things in the model tree. -> a2lus needs documentation and I will document this now.
