### ISSUE TITLE
direction setting has no effect in constraint properties dialog

### ISSUE THREAD

**Issue by donovaly** [kbwbe/A2plus#187]
- select 2 edges
- create a constraint "axisParallel"
- in the appearing dialog change the direction from "aligned" to "opposed"

result: nothing happens

- click on "Flip Dir."

result: now you can see the change in the assembly and also aligned changes to opposed. Nevertheless it should also work when explicitly setting the direction.

**Comment by donovaly** [comment]
OK one can change  "aligned" to "opposed" ad then press "Solve" to see something. But then the dialog is is inconsistent. Either every time you see the result immediately as preview or first after pressing Solve.

**Comment by kbwbe** [comment]
Fixed within devel branch 2019-02-13.
