### ISSUE TITLE
misleading wording in tooltips

### ISSUE THREAD

**Issue by donovaly** [kbwbe/A2plus#188]
The button to make a sphereCenterIdent constraint informs about "spherical surfaces" while the one to make axes coincident speaks about "cylindrical faces" and the one to make axis parallel speak about "cylinderFace".

This is confusing for average users like me. A2plus should therefore use consistently use "face" because a face doesn't have to be a surface. It should be consistently "cylindrical faces" and no camel case (artificial) words like "cylinderFace".

**Comment by kbwbe** [comment]
fixed on masterbranch (merging previous commits too). 2019-02-14
