### ISSUE TITLE
axisPlaneParallel is in most cases not working

### ISSUE THREAD

**Issue by donovaly** [kbwbe/A2plus#189]
- select a linear edge and a plane
- create a axisPlaneParallel constraint

result: the edge will not be parallel to the plane. Both parts will stay as they are. I tried everything with different assemblies and constraint only works rarely for very simple assemblies. With no other constraint I have these problems thus i think there is probably a bug. I will send @kbwbe a test assembly by private mail where the constraints fails (does nothing) no matter what you try to use for the constraint.

**Comment by kbwbe** [comment]
I just tested this constraint again and it is working on my side. I guess that none of your parts had a constraint path to a part with fixed position. If it is still not working for you, please PM me a file.
Thank you.

**Comment by donovaly** [comment]
I already sent you a file via private mail 2 days ago. Have you got it?

**Comment by kbwbe** [comment]
I do not find it. Please send again.

**Comment by donovaly** [comment]
I just resent both to your kbwbe@ mail account. Please send me a reply mail that I know you got it.

**Comment by kbwbe** [comment]
Yes, now i got some mails if files attached.
Thank you.

**Comment by kbwbe** [comment]
I tested the file from your PM. As expected, no part was fixed. Close issue ?

**Comment by donovaly** [comment]
Thank you! I'll close it.
