### ISSUE TITLE
allow vertices in circularEdge constraint

### ISSUE THREAD

**Issue by donovaly** [kbwbe/A2plus#196]
The sphere constraint allows to select either:

* a spherical face and a spherical face
* a spherical face and a vertex
* two vertices

Therefore I see no reason why the circularEdge does not also allow:

* circular edge and circular edge
* circular edge and vertex
* two vertices

Putting the center point of a circular edge onto a vertex is useful.

**Comment by kbwbe** [comment]
This is not ok. A circularEdgeConstraint does a position alignment and also an axis alignment. Last would not work with a vertex.

If such functionality is needed, it would be better to allow circular edges (center point) for the pointIdentity constraint.

**Comment by donovaly** [comment]
> circularEdgeConstraint does a position alignment and also an axis alignment.

Ah, I see.

> If such functionality is needed, it would be better to allow circular edges (center point) for the pointIdentity constraint.

This is reasonable.
Note that I just reported things I wondered about. I can think of applications for such a constraint but this is no must-have.

**Comment by kbwbe** [comment]
Please start new issue when functionality is needed.
