### ISSUE TITLE
deleting constraints make a sound

### ISSUE THREAD

**Issue by donovaly** [kbwbe/A2plus#199]
- use the toolbar button to delete a constraint

Result: you get a confirmation dialog. Unfortunately it appears with the Windows error sound. But there is no error. It is just the confirmation dialog for an action you purposely triggered.

**Comment by kbwbe** [comment]
fixed within devel branch. 2019-02-14

**Comment by donovaly** [comment]
This is not completely fixed in 0.37:

- create a constraint
- in the appearing constraint properties dialog press the button "Delete this constraint"

result: the confirmation dialog issues a sound despite no error occurred - it is just the confirmation of the action you purposely triggered.

**Comment by kbwbe** [comment]
I tested again. I do not get sound on Linux Mint 18.3.
On your system, is it still the windows error sound or now another one ?

**Comment by donovaly** [comment]
I use at the moment Windows 10 and I hear the Windows system sound for "Kritischer Abbruch".

**Comment by donovaly** [comment]
Here is a PR to fix the issue: #210

**Comment by kbwbe** [comment]
PR merged,
Thank you !
