### ISSUE TITLE
inconsistent naming for object Data

### ISSUE THREAD

**Issue by donovaly** [kbwbe/A2plus#201]
A2plus' Data property entries mix small and capital letters:

![a2plus-data](https://user-images.githubusercontent.com/1828501/52815546-3e9e3600-309f-11e9-801e-26a4b5fbc6c5.jpg)

while the other WBs use consistently capital letters. a2plus should also use consistently capital letters.

**Comment by kbwbe** [comment]
The naming cannot be changed without breaking nearly all existing assemblies. This naming scheme is stored within the fcstd-files. I think this issue is not such important compared to breaking existing files.

**Comment by donovaly** [comment]
OK.
