### ISSUE TITLE
inconsistent naming in preferences dialog

### ISSUE THREAD

**Issue by donovaly** [kbwbe/A2plus#202]
The FC preferences dialogs of the different WBs use consistently capital letters at the beginning on an entry. A2plus does mix small and capital letters:

![a2plus-preferences](https://user-images.githubusercontent.com/1828501/52815340-b6b82c00-309e-11e9-9f07-db2db0b19ef5.jpg)

It should follow the other WBs by using consistently capital letters. (personally I also find this looks better).

Moreover the third entry "FixedPosition" must be "fixed Position" or better "Fixed Position", see issue #201.

**Comment by donovaly** [comment]
Here is a PR: #209

**Comment by kbwbe** [comment]
PR merged.
Thank you
