### ISSUE TITLE
The "assembly_hierarchy.html" file location should match assembly path and filename

### ISSUE THREAD

**Issue by ManuelKrause** [kbwbe/A2plus#21]
I'm using an A2plus/solver-stabilization from @kbwbe repo, from sometime this afternoon.

Please use a correct path and filename for the great "assembly_hierarchy.html" according to the processed assembly .fcstd -- instead of using and overwriting the file in the /home/user_xyz/ blindly.

Thank you in advance, 
Manuel

**Comment by kbwbe** [comment]
It is in devel branch now...
