### ISSUE TITLE
Dimensions Draft-WB comes not through subassemblies

### ISSUE THREAD

**Issue by walterwissmann** [kbwbe/A2plus#214]
As the words say:

![dimensions_not_in_masterassy_i](https://user-images.githubusercontent.com/42293697/52889635-30284b00-3181-11e9-9f08-71a2ca23b6f4.jpg)
![dimensions_not_in_masterassy_ii](https://user-images.githubusercontent.com/42293697/52889637-31f20e80-3181-11e9-92a8-8feeafe729c5.jpg)

The dimensioning from the Draft-WB is an everyday tool so they should be able to get through to the master assembly.

Regards
Walter

**Comment by kbwbe** [comment]
Hi Walter,
this is difficult and conflicts with basic concepts of the WB.
If very important, please reopen this issue in the whishlist.
