### ISSUE TITLE
wrong filename in deletion confirmation dialog

### ISSUE THREAD

**Issue by donovaly** [kbwbe/A2plus#215]
- when deleting all constraints from a part view the delete toolbar button I get wrong file names.

Here an example:

![wrong-filename](https://user-images.githubusercontent.com/1828501/52893714-d71bdf80-319f-11e9-9130-8c07b4ea61ec.jpg)

The name of the part is "Bimetal" and not "b_Bimetal_001_"
This is a problem with assemblies where e.g. exist parts names similar to the wrong names in the dialog.

**Comment by kbwbe** [comment]
Fixed within devel branch. 2019-02-16

**Comment by donovaly** [comment]
many thanks
