### ISSUE TITLE
Pictures comes not through subassemblies

### ISSUE THREAD

**Issue by walterwissmann** [kbwbe/A2plus#217]
A way to have a nice realistic look of parts is behind the technique to take pictures at the parts:
![pictures_not_in_master_ii](https://user-images.githubusercontent.com/42293697/52895311-da6f9500-31b8-11e9-8cd0-47892ccc1f04.jpg)
![pictures_not_in_master_i](https://user-images.githubusercontent.com/42293697/52895340-05f27f80-31b9-11e9-892c-c7fe6f27cd7c.jpg)

It is also a day by day tool and pictures should come from subassemblies to the master assembly.

Regards 
Walter

**Comment by kbwbe** [comment]
Hi Walter,
this is difficult and conflicts with basic concepts of the WB.
If very important, please reopen this issue in the whishlist.
