### ISSUE TITLE
enhancement: open FC's save dialog if necessary

### ISSUE THREAD

**Issue by donovaly** [kbwbe/A2plus#234]
- create a new file in FC,, but don't save it yet
- switch to A2plus WB
- use button to add a part

result: A2plus issues a message that one has to save the file first.
It would be nice that it will open FC's file save dialog after one clicks OK in the A2Plus message.

**Comment by kbwbe** [comment]
Done within devel branch. 2019-02-23

**Comment by donovaly** [comment]
Many thanks.
