### ISSUE TITLE
No one parts can't constraint

### ISSUE THREAD

**Issue by Kliurka** [kbwbe/A2plus#247]
No one parts can't constraint, 
I get this message:

```
The highlighted parts where not moved. They are
not constrained (also over constraint chains)
to a fixed part!
```
[lova.zip](https://github.com/kbwbe/A2plus/files/2955640/lova.zip)
 
_OS: Ubuntu 18.04.2 LTS
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.16079 (Git)
Build type: Release
Branch: master
Hash: 6363c90a20b296ab69d7b52230009928199d90df
Python version: 2.7.15rc1
Qt version: 5.9.5
Coin version: 4.0.0a
OCC version: 7.3.0_

**Comment by kbwbe** [comment]
Hi,
there is no valid assembly file within the zip archive (the file does not contain parts imported by A2plus, therefore it does not work). 
Before opening an issue here please study some tutorial videos.
[https://youtu.be/QMxcQ5tssWk](url)
[https://www.youtube.com/watch?v=vDcaFq6IEJM](url)
[https://youtu.be/mnkecA9S7kc](url)
