### ISSUE TITLE
A2plus "move" doesn't use current windows' center focus

### ISSUE THREAD

**Issue by ManuelKrause** [kbwbe/A2plus#253]
Hi people,
here on my Linux FC 0.18 I experience an annoyance:
When having an assembly of e.g. 2 parts, and move 2nd part near enough to select some tiny edges, then zoom in a little more and then, again, use the "move" icon: all previous movement for part2 is gone and it begins at some weird new position for the moved part.

I know, the headline isn't a proper description, but the issue should be fixed !
BR,
Manuel

**Comment by kbwbe** [comment]
Hi Manuel,
if using the move button the part connects to the mouse pointer. When you are moving back from hitting the button the part will first appear in top left corner of 3D view (and not there where you have placed it before). This is normal.

If you do not want to have this effect, please use the FC built in part mover by double clicking the part in the tree view. Then it stays in place until you move it explicitly.

As therefore a solution exists within FC, i will not work on this topic.

**Comment by ManuelKrause** [comment]
Hi Klaus,
thank you for your explanation. This helps a lot !  I just wasn't aware of this solution.
Then you're absolutely right to not bother with this topic.
