### ISSUE TITLE
Workflow for editing parts in assembly

### ISSUE THREAD

**Issue by shortwavedave** [kbwbe/A2plus#255]
Hello,

I don't know if I'm using the right workflow here, so maybe someone can enlighten me. I would like to use the assembly to determine where holes should be drilled, so I add all the parts and orient them how I need, then I edit the parts to add drill. The problem is, and it is mentioned in the readme, is that the constraints break after updating the part. This is an incremental process, so deleting constraints before updating the part, then adding them all back in get's harder and harder. Does anyone have any advice how I should be doing this?

**Comment by kbwbe** [comment]
Hi,
your are welcome. But please do help requests within freecad forum. At this place here we are discussing development of A2plus and fixing of bugs.

Regarding assembly you can do a post here:
[https://forum.freecadweb.org/viewforum.php?f=20](url)

Short remark to you question. If you activate "use experimental topological naming" within preferences of A2plus (from the very beginning before importing first thing to A2plus), less constraints will break.

Also you could do some preliminary work with multiple bodies in part design WB and later import a multi body part to A2plus.

As said before, please do further communication in the FC forum.
