### ISSUE TITLE
FC gears assembly

### ISSUE THREAD

**Issue by 14AUDDIN** [kbwbe/A2plus#260]
when I tried using A2plus with gears made with FC Gears it didn't work, is there a problem with the models made in FC gears or something. Can you make it compatible with FC gears. I wanted to use this for an school project.

**Comment by kbwbe** [comment]
You are not giving really much information related to your problem.
If synchronized movement of connected gears is meant, pure A2plus is not designed to simulate this. You would need to do additional python scripting.
