### ISSUE TITLE
Undo constraint deletion places it in a wronk place in the tree

### ISSUE THREAD

**Issue by abetis** [kbwbe/A2plus#27]
When constraint is added, it appears one level down under the object that it's attached to.
When deleted and after that restored with Undo (Ctrl+Z) the constraint appears as a stand alone leaf in the tree and do not get back to its previous location.

**Comment by kbwbe** [comment]
Added a new command "repair treeview", to be started manually at moment.
Do not know to call it automatically after undo has been done.
Perhaps you know how to do this...

**Comment by abetis** [comment]
Have no clue. We should probably ask about it in the developers corner forum.

**Comment by kbwbe** [comment]
I close this issue, as it is covered by your next one....

**Comment by abetis** [comment]
That one is more specific to constraint placement...
