### ISSUE TITLE
TODO: Explore the UNDO and REDO functionality

### ISSUE THREAD

**Issue by abetis** [kbwbe/A2plus#28]
The WB should register all objects positions to FreeCAD's undo module, so after the assembly user could Ctrl+Z to return to previous positions.
I generally prefer iterative work, so I might want to add a constraint, resolve, see how does it looks like, press Ctrl+Z to get back to the "exploded" situation and add next constraint and so on...

**Comment by kbwbe** [comment]
It is implemented. Please do new issue if you find bugs.
