### ISSUE TITLE
Missing objects to import from FCStd

### ISSUE THREAD

**Issue by sharpener13** [kbwbe/A2plus#289]
Due to multiple FC complications, I tend to use only few methods to create objects in FC:
- sketch (Sketcher)
- extrude (Part)
- boolean (Part)
- clone (Draft)

Unfortunately this leads to issues with A2+. Probably the Draft's clone causes the objects used as a clone source are not shown when trying to import single objects from FCStd (select dialog shown, found object shown, missing some of the objects from FCStd).

There are two objects in the example attached: `HeadBasic` and `HeadAdvanced`. You might want to try to import `HeadBasic`, but it is not shown in the selection dialog. If you delete the `HeadAdvanced` from the FCStd file and save it `HeadBasic` shows up.

Using:
- latest FC 0.19-pre (17352)
- latest A2+ 0.4.25

![ImportDialog](https://user-images.githubusercontent.com/19331387/61186984-217c8c00-a66c-11e9-8208-ed43dcb6b7bb.png)
[a2plus-example.zip](https://github.com/kbwbe/A2plus/files/3390242/a2plus-example.zip)

**Comment by sharpener13** [comment]
Any thoughts or workarounds?

**Comment by kbwbe** [comment]
I can reproduce this issue with your example file. Doing a simple clone is working. But if a feature is added to the clone it's original disappears. I will check the code for this.

**Comment by kbwbe** [comment]
Please update your A2plus WB to version V0.4.26. This should fix the problem. Please test again.

**Comment by sharpener13** [comment]
Cool. It works as expected. Thank you!
