### ISSUE TITLE
Can freely move parts even under constraints

### ISSUE THREAD

**Issue by KoltesDigital** [kbwbe/A2plus#311]
Hi,

Given two objects, fully constraints together, and AutoSolve is on. Selecting one of them and pressing "Move the selected part", it can be freely moved. After pressing "Solves constraints" it goes back in place.

Is it intended? As the AutoSolve tooltip states, solving is only done after adding a new constraints. I'd have expected that it'd be done when moving as well, in order to see how the assembly works. While it's also useful to temporarily break the assembly, this could be achieved by switching off AutoSolve.

**Comment by kbwbe** [comment]
It is the intended behaviour. Sometimes you have to move a part away because it is hiding the geometry with which you want to work on next.

**Comment by KoltesDigital** [comment]
Yes I mentioned that in my last sentence. This behavior can be kept when AutoSolve is switched off. I believe it'd be great to have both behaviors, and to choose between them with the AutoSolve button.

**Comment by kbwbe** [comment]
For me, i am mostly working with AutoSolve on and i need to move parts without solving.
I think it would be better to have a second, different move button for this, where movement triggers solving. But this will be surely slow, as the solver is implemented in pure python.

**Comment by KoltesDigital** [comment]
OK then it makes sense to have another button.

I don't know how solvers are implemented. I thought it would be able to give a list like "this part has TX and RY DOF" so it'd be enough to run it once to know how parts can move without running it again. But even if it's not the case, I think it's worth a try to see whether it's too slow.

**Comment by kbwbe** [comment]
I have added this to my todo list. It will a little bit time, as i am busy with other things.

**Comment by KoltesDigital** [comment]
Sure, it's not a priority feature. Thanks!

**Comment by kbwbe** [comment]
See version v0.4.33
There is a new button "movePartsUnderConstraints". Now you can select a part by mouse and move it around. It is moving according to the constraints of the model.
Please follow the instructions which are shown in the tooltip.

**Comment by KoltesDigital** [comment]
Awesome, thanks!
