### ISSUE TITLE
How to use the constraints?

### ISSUE THREAD

**Issue by leoheck** [kbwbe/A2plus#316]
I love the A2Plus workbench but I never could use the constraints.

I always get this message. No matter what I do. And I don't know what to do. Do you have any tutorials on how to use them?
![image](https://user-images.githubusercontent.com/1277920/70868599-ff5fa080-1f60-11ea-9483-59e003876f59.png)

I am using Freecad 0.19 right now and A2Plus v 0.4.29a (from the master)

**Comment by leoheck** [comment]
I am adding parts with the `Shift+a` shortcut then trying to constraint them. I am starting to think it is wrong because I saw this `Convert a part...` tool which has this yellow-red icon. However, I am not able to constrain the objects after converting them with this tool.

**Comment by kbwbe** [comment]
At least one Part has to have the property "fixed Position" = True. That's all.
