### ISSUE TITLE
"Edit existing constraint" icon isn't reliably available

### ISSUE THREAD

**Issue by justinclift** [kbwbe/A2plus#349]
Experimenting with A2plus (v0.4.42a), and noticed the "Edit selected constraint" icon isn't consistently available (eg sometimes greyed out) when an existing constraint is selected in the Model tab:

![FreeCAD-A2Plus-issue349-Edit_existing_constraint_button_weirdness-0](https://user-images.githubusercontent.com/406299/73769141-497d3980-47ce-11ea-8905-6f26df52d7dc.png)

It **seems** like FreeCAD is opening a "Constraint Properties" dialog when creating the new constraint, but doing so invisibly (and greying out the toolbar icon).

When clicking on a non FreeCAD window (eg to create this issue), then returning to FreeCAD, suddenly the dialog becomes visible:

![FreeCAD-A2Plus-issue349-Edit_existing_constraint_button_weirdness-1](https://user-images.githubusercontent.com/406299/73768243-c6a7af00-47cc-11ea-9d88-d0716c48b4d7.png)

Pretty sure that dialog should be immediately visible, instead of only being shown when switching away from FreeCAD and back to it.

**Comment by justinclift** [comment]
[Oops, pressed Enter when switching between windows and accidentally created this issue prior to having all the info ready.  Still collecting info, for filling out this issue.]

**Comment by kbwbe** [comment]
Hi,
i tested this but cannot reproduce the effect. The dialog appears always. When it is visible, the toolbar icon is greyed out. When i close the dialog, the toolbar icon gets active again.

For test i compiled a fresh FreeCAD:

OS: Linux Mint 19.2 (X-Cinnamon/cinnamon)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.19478 (Git)
Build type: Unknown
Branch: master
Hash: e6a29986eb7caf569b9353e997f310c1c2efbec8
Python version: 3.6.9
Qt version: 5.9.5
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: German/Germany (de_DE)

**Comment by kbwbe** [comment]
I will have a look at this during my work with A2plus next days (also on other machines)

**Comment by justinclift** [comment]
No worries. :smile:

It's possible it's something weird with my system, though it would be a bit surprising as it's not a behaviour I've yet seen from any other application.  I'll try with an updated (again) git compile from newer master in the next few days too.  Just in case it was an unfortunate point in time that I compiled from or something. :smile:

**Comment by kbwbe** [comment]
Please open a new issue if the problem persists.
