### ISSUE TITLE
The badges in the README.md are bronken.

### ISSUE THREAD

**Issue by leoheck** [kbwbe/A2plus#371]
![image](https://user-images.githubusercontent.com/1277920/77345048-dd6d7b00-6d12-11ea-9051-90ba56edf84c.png)

**Comment by luzpaz** [comment]
@leoheck  Can't reprodice. Try hard refreshing

**Comment by leoheck** [comment]
I was seeing like that since many days ago,
Now it looks ok :)

![image](https://user-images.githubusercontent.com/1277920/77372546-9c8e5a00-6d44-11ea-83e8-783fe2d08abd.png)
