### ISSUE TITLE
A2Plus still shows parts that are hidden in the imported file.

### ISSUE THREAD

**Issue by leoheck** [kbwbe/A2plus#372]
I thought you had fixed this, but right now I am facing the same issue.
Using version 0.4.45.c (with Freecad 0.19)

**Comment by leoheck** [comment]
Actually it happnes with Part Workbench objects.

**Comment by kbwbe** [comment]
Without more information i cannot check where the problem is coming from.
Please provide a small sample file.

**Comment by leoheck** [comment]
I was using version Freecad 0.18 by mistake instead of my default 0.19 so maybe the plugin was not upgraded to the last version. If this issue happens again I will come here with better info. I will keep it closed by now.
