### ISSUE TITLE
Parts inside the Yellow Part (group) are not hidden in the imported file

### ISSUE THREAD

**Issue by leoheck** [kbwbe/A2plus#385]
I am Importing a file with the Yellow Part (I don't know the right name of it) which has 2 other objects inside. This Yellow Part is hidden as shown in the following image. But A2Plus is importing the parts, they should be hidden or not imported. I am using A2Plus 0.4.47

![image](https://user-images.githubusercontent.com/1277920/81461693-e790ef00-9183-11ea-8348-6c1f2fbb8543.png)

**Comment by kbwbe** [comment]
this should be done with version 0.4.47h
