### ISSUE TITLE
A2Plus seems to be removing "_top" string front the file name to label the imported part.

### ISSUE THREAD

**Issue by leoheck** [kbwbe/A2plus#396]
Maybe it is the 3rd issue I am posting regarding the same thing. 

I have one external model called `case_top.FCStd`
When I import it, it is labeled as `case_001` instead of `case_001`
When I import other parts it reuses the name as usual as in `case_bottom.FCStd` that is imported as `case_bottom_001`

So, quick question, is it possible that A2Plus is removing the `_top` for any reason?

![image](https://user-images.githubusercontent.com/1277920/94850512-69b4d500-03fd-11eb-8fbb-5537a2b61790.png)

**Comment by kbwbe** [comment]
I did a quick test and indeed "_top" at the end of an filename is filtered away. I have to investigate that behaviour. I do not think that i have implemented this. So it is very strange.

**Comment by kbwbe** [comment]
I found a bug within the code. I will try to fix it next days.

**Comment by leoheck** [comment]
Yay! This cool. Jut let me know if i can help you with something, or at least test it when you change something.

**Comment by kbwbe** [comment]
I have fixed this issue right now.

**Comment by leoheck** [comment]
Looking good kbwbe, thanks! This issue is annoying me for so long time.
