### ISSUE TITLE
improve parallel

### ISSUE THREAD

**Issue by Turro75** [kbwbe/A2plus#4]
Hello,

any chance to insert a plane to line parallel constraints?

![image](https://user-images.githubusercontent.com/10894566/42232095-b3fe2b1c-7eed-11e8-9018-189f39f9d0d8.png)

**Comment by kbwbe** [comment]
Hello Turro75, thanks for testing :)
Should be possible. I will implement it next versions.

**Comment by kbwbe** [comment]
New constraint axisPlaneParallel has been done within Release V0.1.8
