### ISSUE TITLE
Could not move some parts

### ISSUE THREAD

**Issue by gaminn** [kbwbe/A2plus#411]
OS: Windows 10
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.4 (GitTag)
Build type: Release
Branch: releases/FreeCAD-0-18
Hash: 980bf9060e28555fecd9e3462f68ca74007b70f8
Python version: 3.6.6
Qt version: 5.6.2
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: Czech/CzechRepublic (cs_CZ)

File wheel_bearing2 from [assembly.zip](https://github.com/kbwbe/A2plus/files/5935502/assembly.zip). When adding constraint for bearing_003 and bearing_004, I get Could not move some parts, The highlighted parts were not moved. They are not constrained (also over constraint chains) to a fixed part!

![error](https://user-images.githubusercontent.com/20270888/107092762-71014a80-6804-11eb-9c90-2d8888c1417a.png)

**Comment by kbwbe** [comment]
Please see the answer within the FC-Forum: [https://forum.freecadweb.org/viewtopic.php?f=20&t=55246&p=474915#p474915](url)
