### ISSUE TITLE
Offset a real value

### ISSUE THREAD

**Issue by fandres** [kbwbe/A2plus#431]
Is there a possibility to do the "offset" a real value? It is required for Song President

**Comment by kbwbe** [comment]
I have difficulties to understand the problem. You already can enter real values to constraints' offsets. If the precision of 2 digits isn't enough, you can enter more precise values directly to the field offset within the constraints' property editor.

Are you using a recent Version of A2plus ? Otherwise you shoud update it.

**Comment by fandres** [comment]
![Screenshot_20210508_091433](https://user-images.githubusercontent.com/7121772/117542370-f819b680-afdd-11eb-8b4b-83614f9d13dd.png)
I'm trying to restrict two planes: I need a 2.35mm offset but it does not allow me floating point, huh attempted with "coma", and "point". 
A2+Plus V0.4.5

**Comment by kbwbe** [comment]
What is your A2plus version ? It is displayed within the workbench selector widget.

**Comment by fandres** [comment]
A2Plus:
![Screenshot_20210508_134744](https://user-images.githubusercontent.com/7121772/117550115-0da1d700-b004-11eb-91ea-85a0b1f7b0b0.png)
V0.4.53a 

Freecad:
OS: Debian GNU/Linux 10 (buster) (KDE//usr/share/xsessions/plasma)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.504.24301 +3597 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: 540995a6e8d5db01dfe2597439ec3131ca69b030
Python version: 3.8.8
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.4.0
Locale: Spanish/Colombia (es_CO)

**Comment by kbwbe** [comment]
FC Version: 2021.504.24301 +3597 (Git) AppImage
Build type: Release
Branch: LinkDaily

RealThunder's FC branch ?
A2plus is tested with FC-0.16 ... FC-0.19.2, but not with the RT-branch. Perhaps this is the reason why offset precision is not working.

**Comment by fandres** [comment]
Branch: LinkStage3 + assembly3

Download:
https://github.com/realthunder/FreeCAD_assembly3/releases/tag/0.11

I also have Freecad 0.19 Evre if it also happens. It is possible that it is due to a point or coma problem

**Comment by kbwbe** [comment]
I had a little bit time and tested input of real values to planeCoincident constraint on LinkStage3/Daily
It worked out of the box. Please see following screenshot:

![LinkDaily-planeCoincident-offset](https://user-images.githubusercontent.com/40606725/118109914-10c10c80-b3e2-11eb-9aa0-a3c2e1ae4b07.png)

Did you set the FC Prefences correctly ?
Preferences/General/Units => Number of decimals

![Preferences](https://user-images.githubusercontent.com/40606725/118110173-61d10080-b3e2-11eb-8467-580531f93344.png)

A2plus is sensitive to that value.

**Comment by fandres** [comment]
Hello
I have corroborated and with the cube it works 
![git_f](https://user-images.githubusercontent.com/7121772/118271369-c6459b80-b486-11eb-967d-7ed6d6a1db47.png)

The project that was creating does not work.
Eliminated the directory and reinstalled A2plus already worked, I do not know what was wrong. I was alienating a .step and a piece created in part desing workbench 
![freecad-git2](https://user-images.githubusercontent.com/7121772/118273161-3d7c2f00-b489-11eb-908a-72017a6a7981.png)

You have been very attentive. Thanks

**Comment by kbwbe** [comment]
You are welcome.
