### ISSUE TITLE
A2plus does not support translation

### ISSUE THREAD

**Issue by WandererFan** [kbwbe/A2plus#44]
At some point, we will need to add 
def translate(context, text, disambig=None):
    return QtCore.QCoreApplication.translate(context, text, disambig)
and
QtCore.QT_TRANSLATE_NOOP()

to allow dialogs and tooltips to be displayed in user's preferred language.

**Comment by luzpaz** [comment]
https://forum.freecadweb.org/viewtopic.php?f=10&t=36413

related: https://github.com/shaise/FreeCAD_SheetMetal/issues/99

**Comment by luzpaz** [comment]
Some headway was made in the [forum thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=36413&start=10#p375856). The solution (here's an example from the BIM WB:

```
        FreeCADGui.addLanguagePath(BimCommands.getLanguagePath())
        Log ('Loading BIM module... done\n')
        FreeCADGui.updateLocale() # refresh the language according to current locale.
```

**Comment by luzpaz** [comment]
@yorikvanhavre started a wiki page https://wiki.freecadweb.org/Translating_an_external_workbench

**Comment by luzpaz** [comment]
Started working on this at https://github.com/kbwbe/A2plus/pull/416  
Feel free to help, my branch is at https://github.com/luzpaz/A2plus/tree/translation

**Comment by kbwbe** [comment]
Preparations are done within #421

**Comment by luzpaz** [comment]
What's left to do?

**Comment by kbwbe** [comment]
The translation does not work.

**Comment by luzpaz** [comment]
@kbwbe is this ticket obsolete now ?

**Comment by kbwbe** [comment]
@luzpaz: I think @PushKK  did the job.

**Comment by luzpaz** [comment]
The this ticket is obsolete
