### ISSUE TITLE
A2Plus does not support system undo/redo facility

### ISSUE THREAD

**Issue by WandererFan** [kbwbe/A2plus#45]
At some point, we will need to add the undo/redo stack when we update the model:

        FreeCAD.ActiveDocument.openTransaction("Add a2p part")
        FreeCADGui.doCommand('obj  = a2p.command1()')
        FreeCADGui.doCommand(obj  =  a2p.command2()'
        FreeCAD.ActiveDocument.commitTransaction()

**Comment by kbwbe** [comment]
Most important parts of A2p now support system undo/redo, as they are:
* solving
* updateImportParts
This in master branch since 2018-10-20
