### ISSUE TITLE
A2plus assumes access to `$HOME/icons/`

### ISSUE THREAD

**Issue by luzpaz** [kbwbe/A2plus#462]
This has to do with @DanMiel's recent code contribution  
Here's the background: 
* https://github.com/ppd/freecad-ppd/issues/29
* https://forum.freecadweb.org/viewtopic.php?p=585577#p585577

**Comment by kbwbe** [comment]
I just fixed that. Please update to V04.55b.

**Comment by luzpaz** [comment]
Indeed! Solved in v04.55b  
Thanks @kbwbe
