### ISSUE TITLE
ModuleNotFoundError: No module named 'A2plus'

### ISSUE THREAD

**Issue by henk23** [kbwbe/A2plus#476]
Using FreeCAD 0.19 on macOS 12.3.1

The problem happens when trying to `import A2plus.a2p_solversystem as a2p_solver` in python script.

```
sys.version
'3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 21:16:28) \n[Clang 11.1.0 ]'

sys.path
-> Array includes '/Users/[myuser]/Library/Preferences/FreeCAD/Mod/A2plus'
```

Is there a problem on my machine or is this a bug of A2plus?

**Comment by kbwbe** [comment]
Use this:

 import FreeCAD.A2plus.a2p_solversystem as a2p_solver
