### ISSUE TITLE
PlaneCoincident not working in A2Plus 0.4.55 & 0.4.56

### ISSUE THREAD

**Issue by easyprototype** [kbwbe/A2plus#480]
Hello. I am using FreeCAD 0.19 under Windows 10.

When I click on planeCoincident to add this constraint, the usual dialog box does not appear and I get the following error message:

"09:06:46  Running the Python command 'a2p_PlaneCoincidentConstraintCommand' failed:
Traceback (most recent call last):
  File "C:\Program Files\FreeCAD 0.19\Mod\A2plus-0.4.56\a2p_constraintcommands.py", line 319, in Activated
    cvp = a2p_constraintDialog.a2p_ConstraintValuePanel(
  File "C:\Program Files\FreeCAD 0.19\Mod\A2plus-0.4.56\a2p_constraintDialog.py", line 936, in __init__
    self.cvw = a2p_ConstraintValueWidget(
  File "C:\Program Files\FreeCAD 0.19\Mod\A2plus-0.4.56\a2p_constraintDialog.py", line 74, in __init__
    self.initUI()
  File "C:\Program Files\FreeCAD 0.19\Mod\A2plus-0.4.56\a2p_constraintDialog.py", line 150, in initUI
    user_qty, user_unit = userPreferred.split(' ')

not enough values to unpack (expected 2, got 1)"

However after that if I click on the SolveContraints button, the part moves in space and is oriented/constrained correctly. When I use another constraints button (like PlanesParallel), the menu appears normally and the part is immediately moved as usual.

A2Plus 0.4.50 is the last version where planeCoincident works without an error message.

**Comment by kbwbe** [comment]
Thank you. Please update to version 0.4.56a. The issue should be fixed.

**Comment by easyprototype** [comment]
I don't know exactly where to find 0.4.56a (releases stop at 0.4.56) so I used the addon manager to update A2Plus. I don't know which version I have but the new "onebutton" is there and the "PlaneCoincident" function now works perfectly. I also tried the onebutton feature and I must say that selecting multiple constraints without using the CTRL key is super nice! Thank you!

One last thing: how can I check which version of A2Plus I have installed?

**Comment by kbwbe** [comment]
Updating the workbench via the addon manager was the right way. You always get the newest version.
Unfortunately you cannot see the version directly anymore when using FC0.19.x. There is a file called package.xml within the source code of A2plus. The version is written inside.
When using FC0.20, i think there is a way to show the version of all installed workbenches in the about dialogs.
But i did not use FC0.20 up to date and will change a bit later. So you have to try by your self.

**Comment by easyprototype** [comment]
Yes, I see 0.4.56a in the .XML. Let's hope the future versions of FreeCAD display the workbenches' version readily.
