### ISSUE TITLE
module 'PySide.QtGui' has no attribute 'QDesktopWidget'

### ISSUE THREAD

**Issue by leybodv** [kbwbe/A2plus#645]
At the very beginning of work with the A2plus, when I apply any constrain, the exception is thrown:

> 09:07:03  Initializing A2plus Workbench v0.4.67.
> 09:11:10  Running the Python command 'a2p_PlaneCoincidentConstraintCommand' failed:
> Traceback (most recent call last):
>   File "/home/d/.local/share/FreeCAD/Mod/A2plus/./a2p_ConstraintCommands.py", line 336, in Activated
>     cvp = a2p_ConstraintDialog.a2p_ConstraintValuePanel(
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/d/.local/share/FreeCAD/Mod/A2plus/./a2p_ConstraintDialog.py", line 951, in __init__
>     self.move(getMoveDistToStoredPosition(self))
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/d/.local/share/FreeCAD/Mod/A2plus/./a2p_ConstraintDialog.py", line 900, in getMoveDistToStoredPosition
>     fcFrame = QtGui.QDesktopWidget.geometry(mw)
>               ^^^^^^^^^^^^^^^^^^^^
> 
> module 'PySide.QtGui' has no attribute 'QDesktopWidget'

I can work afterwards, although sometimes program crushes silently.

**Versions:**
FreeCad 1.0.0RC1
Operating System Archlinux
Qt 6.7.2
A2plus 0.4.67

**Comment by kbwbe** [comment]
The Fix has been merged. Please update A2plus WB
