### ISSUE TITLE
file importer should create compounds instead of disassembling/assembling faces

### ISSUE THREAD

**Issue by kbwbe** [kbwbe/A2plus#96]

**Comment by ManuelKrause** [comment]
@kbwbe 
I've tested your approach posted to the forum for a while. With my FC 0.17 & A2plus assemblies I see the same advantages as with my former "improve-color-import" approach (now in devel-extended-colormanagement).
I still may need more testing, e.g. regarding FC 0.16 files or old assemblies.
With this posting I just want to add the portion of code as a .diff, so it doesn't get lost. It's based on A2plus devel branch from 20180911.

Best regards,
Manuel

[A2plus.extended-color-management-simple.20180911.diff.txt](https://github.com/kbwbe/A2plus/files/2386587/A2plus.extended-color-management-simple.20180911.diff.txt)

**Comment by ManuelKrause** [comment]
I still can recommend this compound-shape approach, as it preserves diffuseColors with proper transparencies in FC 0.17 assemblies and sub-assemblies.

Here I just want to provide actualized versions for the devel branch of 20181002:
The patch: [A2plus.extended-color-management-simple.MOD-20180916.diff.txt](https://github.com/kbwbe/A2plus/files/2441653/A2plus.extended-color-management-simple.MOD-20180916.diff.txt)
The file: [a2p_MuxAssembly.20181002.py.txt](https://github.com/kbwbe/A2plus/files/2441664/a2p_MuxAssembly.20181002.py.txt)

Please remove the .txt (and for the file the date suffix, too) for use. They don't import from my system without .txt

**Comment by kbwbe** [comment]
As it is needed for topological naming, disassembling/assembling faces during MUX will stay in code next time.
